;region Metadata
[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1
SkinWidth=820

[Metadata]
Name=KanbanBoard

[MeasureScript]
Measure=Script
ScriptFile=#@#Kanban.lua
;endregion


;region Styles
[StyleColumnHeaderBackground]
Shape=Rectangle 0,0,220,36,6 | Fill Color 45,45,45,255 | StrokeWidth 1 | Stroke Color 90,90,90,255

[StyleColumnHeader]
FontFace=Segoe UI
FontSize=14
FontColor=255,255,255,255
AntiAlias=1
StringStyle=Bold
StringWidth=200

[StyleCardBackground]
Shape=Rectangle 0,0,220,72,8 | Fill Color 40,40,40,220 | StrokeWidth 1 | Stroke Color 90,90,90,255
DynamicVariables=1

[StyleCardSummary]
FontFace=Segoe UI
FontSize=11
FontColor=255,255,255,255
AntiAlias=1
ClipString=2
StringWidth=200
DynamicVariables=1

[StyleCardProjectBackground]
ProjectBgModifiers=Fill Color 10,10,10,220 | StrokeWidth 0 | Stroke Color 90,90,90,255

[StyleCardProject]
Shape=Rectangle 0,0,220,72,8 | Fill Color 40,40,40,220 | StrokeWidth 1 | Stroke Color 90,90,90,255
FontFace=Segoe UI
FontSize=9
FontColor=170,170,170,255
AntiAlias=1
ClipString=1
StringWidth=200
DynamicVariables=1
;endregion


;region Column Headers
[MeterAddTodoBackground]
Meter=Shape
Shape=Ellipse 40,38,18 | Fill Color 40,40,40,220 | StrokeWidth 1 | Stroke Color 90,90,90,255
LeftMouseUpAction=[!CommandMeasure "MeasureTodoSummaryInput" "ExecuteBatch 1"]

[MeterAddTodo]
Meter=Image
ImageName=#@#Images\plus.png
X=27
Y=26
W=25
H=25
LeftMouseUpAction=[!CommandMeasure "MeasureTodoSummaryInput" "ExecuteBatch 1"]
PreserveAspectRatio=1

[MeterTodoHeaderCard]
Meter=Shape
MeterStyle=StyleColumnHeaderBackground
X=60
Y=20
W=200
H=34
LeftMouseUpAction=[!CommandMeasure MeasureScript "DropTask(1)"]

[MeterTodoHeader]
Meter=String
MeterStyle=StyleColumnHeader
Text=TO DO
X=70
Y=27
LeftMouseUpAction=[!CommandMeasure MeasureScript "DropTask(1)"]

[MeterInProgressHeaderCard]
Meter=Shape
MeterStyle=StyleColumnHeaderBackground
X=300
Y=20
W=200
H=34
LeftMouseUpAction=[!CommandMeasure MeasureScript "DropTask(2)"]

[MeterInProgressHeader]
Meter=String
MeterStyle=StyleColumnHeader
Text=IN PROGRESS
X=310
Y=27
LeftMouseUpAction=[!CommandMeasure MeasureScript "DropTask(2)"]

[MeterDoneHeaderCard]
Meter=Shape
MeterStyle=StyleColumnHeaderBackground
X=540
Y=20
W=200
H=34
LeftMouseUpAction=[!CommandMeasure MeasureScript "DropTask(3)"]

[MeterDoneHeader]
Meter=String
MeterStyle=StyleColumnHeader
Text=DONE
X=550
Y=27
LeftMouseUpAction=[!CommandMeasure MeasureScript "DropTask(3)"]

[MeterClearDoneBackground]
Meter=Shape
Shape=Ellipse 780,38,18 | Fill Color 40,40,40,220 | StrokeWidth 1 | Stroke Color 90,90,90,255
LeftMouseUpAction=[!CommandMeasure MeasureScript "ClearDoneTasks()"]

[MeterClearDone]
Meter=Image
ImageName=#@#Images\delete.png
X=767
Y=24
W=25
H=25
LeftMouseUpAction=[!CommandMeasure MeasureScript "ClearDoneTasks()"]
PreserveAspectRatio=1
;endregion


; region Task Meters
[TaskBg1]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary1]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg1]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject1]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg2]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary2]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg2]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject2]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg3]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary3]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg3]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject3]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg4]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary4]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg4]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject4]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg5]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary5]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg5]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject5]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg6]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary6]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg6]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject6]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg7]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary7]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg7]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject7]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg8]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary8]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg8]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject8]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg9]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary9]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg9]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject9]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg10]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary10]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg10]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject10]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg11]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary11]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg11]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject11]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg12]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary12]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg12]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject12]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg13]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary13]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg13]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject13]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg14]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary14]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg14]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject14]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg15]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary15]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg15]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject15]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg16]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary16]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg16]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject16]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg17]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary17]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg17]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject17]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg18]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary18]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg18]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject18]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg19]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary19]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg19]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject19]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg20]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary20]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg20]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject20]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg21]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary21]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg21]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject21]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg22]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary22]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg22]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject22]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg23]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary23]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg23]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject23]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg24]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary24]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg24]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject24]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg25]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary25]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg25]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject25]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg26]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary26]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg26]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject26]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg27]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary27]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg27]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject27]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg28]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary28]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg28]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject28]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg29]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary29]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg29]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject29]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks


[TaskBg30]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskSummary30]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProjectBg30]
Meter=Shape
Hidden=1
DynamicVariables=1
Group=Tasks

[TaskProject30]
Meter=String
Hidden=1
DynamicVariables=1
Group=Tasks
;endregion


;region Todo Input
[MeasureTodoSummaryInput]
Measure=Plugin
Plugin=InputText
X=27
Y=26
W=200
H=22
FontSize=12
SolidColor=40,40,40,255
FontColor=255,255,255,255
DefaultValue=Please enter task summary...
FocusDismiss=1
Command1=[!CommandMeasure "MeasureScript" "SetPendingSummary([[$UserInput$]])"][!CommandMeasure "MeasureTodoProjectInput" "ExecuteBatch 1"]

[MeasureTodoProjectInput]
Measure=Plugin
Plugin=InputText
X=27
Y=26
W=200
H=22
FontSize=12
SolidColor=40,40,40,255
FontColor=255,255,255,255
DefaultValue=Please enter task project...
FocusDismiss=1
Command1=[!CommandMeasure "MeasureScript" "SetPendingProject([[$UserInput$]])"]
;endregion